# Meta Data for SEO

## Homepage
title = "GlimBoi"
titleSeparator = "-"
titleAddition = "Chatbot for Glimesh.tv"
description = "GlimBoi is an all in one chatbot for Glimesh.tv"

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "MythoGM"
twitterCreator = "MythoGM"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "en_US"
facebook = false

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/MythoGM"
schemaGitHub = "https://github.com/aMytho"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/aMytho/GlimBoi"
editPage = false
